### ISSUE TITLE
synchronizing audigram with mediaplayer

### ISSUE THREAD

**Issue by parsa10** [alxrm/audiowave-progressbar#21]
hey man , thanks for your awesome library . i have implemented my player and im getting the mp3 file by url and then i convert it to ByteArray and use  `audioWave.setOnProgressListener(...);` . but when i implement it like seekbar i encounter with some problems , here is my code : 

```
public class Mp3PageFragment extends Fragment {

    private View rootView;
    private MediaPlayer mediaPlayer;
    private SeekBar seekBar;
    private TextView currentTime;
    private TextView totalTime;
    private Timer timer;
    private ImageView playButton;
    private ImageView forwardButton;
    private ImageView rewindButton;
    private BlobVisualizer mVisualizer;
    private AudioWaveView audioWaveView;

    @Override
    @Nullable
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        if (rootView == null) {

            rootView = inflater.inflate(R.layout.mp3_page_fragment, container, false);
            setUpViews();
            setUpMediaPlayer();

        }

        return rootView;
    }

    private void setUpViews() {

        setBackgroundImage("http://20dl.pw/2019/02/Overdose%25203-realThumb_20.jpg");
        setImage("http://20dl.pw/2019/02/Overdose%25203-realThumb_20.jpg");

        playButton = rootView.findViewById(R.id.iv_mp3_page_play_pause);
        forwardButton = rootView.findViewById(R.id.iv_mp3_page_skip_next);
        rewindButton = rootView.findViewById(R.id.iv_mp3_page_skip_previous);
        //seekBar = rootView.findViewById(R.id.sb_mp3_page_seek_bar);
        currentTime = rootView.findViewById(R.id.tv_mp3_page_current_time);
        currentTime.setText(formatDuration(0));
        totalTime = rootView.findViewById(R.id.tv_mp3_page_total_time);
        timer = new Timer();
        timer.schedule(new MainTimer(), 0, 1000);
        mVisualizer = rootView.findViewById(R.id.blast);
        audioWaveView = rootView.findViewById(R.id.sb_mp3_page_seek_bar);
    }

    private void setUpMediaPlayer() {

        mediaPlayer = new MediaPlayer();

        try {

            mediaPlayer.setDataSource(rootView.getContext(), Uri.parse("http://20dl.pw/2019/02/04%20-%20YAS%20-%20Esalat.mp3"));

            mediaPlayer.prepareAsync();

            mediaPlayer.setOnPreparedListener(mediaPlayer -> {

                setUpMediaPlayerElements();

                int audioSessionId = mediaPlayer.getAudioSessionId();
                if (audioSessionId != -1)
                    mVisualizer.setAudioSessionId(audioSessionId);

            });

            mediaPlayer.setOnCompletionListener(mediaPlayer -> {

                playButton.setImageDrawable(ContextCompat.getDrawable(rootView.getContext(), R.drawable.ic_mp3_page_play_arrow_white_24dp));
                mediaPlayer.seekTo(0);
            });

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void setUpMediaPlayerElements() {

        playButton.setOnClickListener(view -> {

            if (mediaPlayer.isPlaying()) {

                mediaPlayer.pause();
                playButton.setImageDrawable(ContextCompat.getDrawable(rootView.getContext(), R.drawable.ic_mp3_page_play_arrow_white_24dp));

            } else {

                mediaPlayer.start();
                playButton.setImageDrawable(ContextCompat.getDrawable(rootView.getContext(), R.drawable.ic_mp3_page_pause_black_24dp));

            }

        });

        forwardButton.setOnClickListener(view -> {

            mediaPlayer.seekTo(mediaPlayer.getCurrentPosition() + 5000);

        });

        rewindButton.setOnClickListener(view -> {

            mediaPlayer.seekTo(mediaPlayer.getCurrentPosition() - 5000);

        });

        try {

            byte[] myByte = downloadFile(new URL("http://20dl.pw/2019/02/04%20-%20YAS%20-%20Esalat.mp3"));
            assert myByte != null;
            audioWaveView.setRawData(myByte);

        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        audioWaveView.setExpansionDuration(mediaPlayer.getDuration());

        audioWaveView.setOnProgressListener(new OnProgressListener() {
            @Override
            public void onStartTracking(float v) {


            }

            @Override
            public void onStopTracking(float v) {

            }

            @Override
            public void onProgressChanged(float v, boolean b) {

                if (b) {

                    mediaPlayer.seekTo((int) (v * 1000));

                }

            }
        });

        totalTime.setText(formatDuration(mediaPlayer.getDuration()));

    }

    private void setImage(String url) {


        SimpleDraweeView image = rootView.findViewById(R.id.sdv_mp3_page_image);
        image.setImageURI(Uri.parse(url));

    }

    private void setBackgroundImage(String url) {

        SimpleDraweeView backgroundImage = rootView.findViewById(R.id.sdv_mp3_page_background_blur_image);

        Uri uri1 = Uri.parse(url);

        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri1)
                .setPostprocessor(new IterativeBoxBlurPostProcessor(20))
                .build();

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setOldController(backgroundImage.getController())
                .build();

        backgroundImage.setController(controller);

    }

    private String formatDuration(long duration) {

        int seconds = (int) (duration / 1000);
        int minutes = seconds / 60;
        seconds %= 60;
        return String.format(Locale.ENGLISH, "%02d", minutes) + ":" + String.format(Locale.ENGLISH, "%02d", seconds);
    }

    @Override
    public void onDestroyView() {
        mediaPlayer.release();
        timer.purge();
        timer.cancel();


        super.onDestroyView();
    }

    public static byte[] downloadFile(URL url) {

        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();

        StrictMode.setThreadPolicy(policy);

        try {
            URLConnection conn = url.openConnection();
            conn.setConnectTimeout(5000);
            conn.setReadTimeout(5000);
            conn.connect();

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            IOUtils.copy(conn.getInputStream(), baos);

            return baos.toByteArray();
        } catch (IOException e) {
            // Log error and return null, some default or throw a runtime exception
        }

        return null;
    }

    private class MainTimer extends TimerTask {


        @Override
        public void run() {

            Objects.requireNonNull(getActivity()).runOnUiThread(() -> {

                int mCurrentPosition = mediaPlayer.getCurrentPosition() / 1000;
                audioWaveView.setProgress(mCurrentPosition);
                currentTime.setText(formatDuration(mediaPlayer.getCurrentPosition()));

            });
        }
    }

}

```
every Thing works fine But As you can see i implement  `audioWaveView.setProgress(mediaPlayer.getCurrentPosition());` into the class timer to show streaming process but it makes this error : 

```
2019-02-18 12:46:48.172 27403-27403/com.parsa.bistrap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.parsa.bistrap, PID: 27403
    java.lang.IllegalArgumentException: Progress must be in 0..100
        at rm.com.audiowave.AudioWaveView.setProgress(AudioWaveView.kt:79)
        at com.parsa.bistrap.fragments.mp3page.Mp3PageFragment$MainTimer.lambda$run$0(Mp3PageFragment.java:269)
        at com.parsa.bistrap.fragments.mp3page.-$$Lambda$Mp3PageFragment$MainTimer$QWa9_ReuC5VaKITz2IOpWbSu168.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```
and i think the problem is for `audioWaveView.setProgress();` this method accept numbers between 0 to 100 but the` mediaPlayer.getCurrentPosition()` is returning outranged number . in seekbar there was a method called : seekbar.setMax(MediaPlayer.getDuration()), but there is no such thing in your library , can you please tell me how to change that accepted number dynamically for set process ? Thanks <3

**Comment by alxrm** [comment]
@parsa10 pretty easy: 

```java
final float audioWaveProgress = (currentPosition / (float) duration) * 100F;
audioWaveView.setProgress(audioWaveProgress);
```

Also I see you have this line:

```java
audioWaveView.setExpansionDuration(mediaPlayer.getDuration());
```

Seems like an incorrect usage of this property, be careful, it's for bars height animation.

**Comment by alxrm** [comment]
Since issue is not related to the library itself — I'm closing it, also the problem seems to be solved

**Comment by parsa10** [comment]
Wow thanks for your quick awesome response <3 
And i had 2 questions , it will be great if you would give me some tips : 
In the setOnProgress Listener in onProgressChanged , what should i write to change the progress of MediaPlayer ? because the code that i wrote is not working .
*****************************
And i'm receiving the Mp3 file from server by an URL , and i have to wait for mediaPlayer to compeletly prepare and download the mp3 and then audiogram will be displayed and it takes time to download the file completely . is there anyway to reduce its time ? Or draw it on Runtime dynamically ? 
Thank you very much for your helps
