### ISSUE TITLE
WaveView on RecyclerView

### ISSUE THREAD

**Issue by EMIN3M1986** [alxrm/audiowave-progressbar#3]
Hi. There is a problem when using waveview on scrolling recyclerview .

    ` java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                  at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
                                                                  at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
                                                                  at rm.com.audiowave.AudioWaveView.onDraw(AudioWaveView.kt:132)
                                                                  at android.view.View.draw(View.java:16302)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15284)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.draw(View.java:16305)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15284)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.draw(View.java:16305)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15284)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4400)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.draw(View.java:16305)
                                                                  at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3792)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15284)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.draw(View.java:16305)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15284)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15279)
                                                                  at android.view.View.draw(View.java:16072)
                                                              	at android.view.ViewGroup.d`

**Comment by rolandvar** [comment]
Same issure, No solution yet?

**Comment by alxrm** [comment]
Sorry guys, I've recently had lack of time

Now I'm more free, so I can investigate this issue, sorry for long time no answering

**Comment by alxrm** [comment]
I uploaded `0.8` version of this, which contains the fix of this issue

I'll close this one, if anything else goes wrong, just let me know 

And sorry for inconvenience
